export default {
  EXPORT_DIAGRAM_PYTHON: 'EXPORT_DIAGRAM_PYTHON',
  EXPORT_DIAGRAM_JSON: 'EXPORT_DIAGRAM_JSON',
  ADD_NODE: 'ADD_NODE',
  IMPORT_DIAGRAM: 'IMPORT_DIAGRAM',
  SHARE_DIAGRAM: 'SHARE_DIAGRAM',
  IMPORT_DIAGRAM_FROM_URL: 'IMPORT_DIAGRAM_FROM_URL',
  GET_EXPORT_PARAMETERS: 'GET_EXPORT_PARAMETERS',
  EXPORT_DIAGRAM_FAIL: 'EXPORT_DIAGRAM_FAIL',
};
