export default {
  EXPORT_DIAGRAM_PYTHON: 'EXPORT_DIAGRAM_PYTHON',
  EXPORT_DIAGRAM_JSON: 'EXPORT_DIAGRAM_JSON',
  ADD_NODE: 'ADD_NODE',
  IMPORT_DIAGRAM: 'IMPORT_DIAGRAM',
  SHARE_DIAGRAM: 'SHARE_DIAGRAM',
};
